{% set version = "1.0.0" %}

package:
  name: ipylab
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipylab/ipylab-{{ version }}.tar.gz
  sha256: c4f0744b1f96d6c4605b986aa59ebccd64451bf71c9483a019ab7a52c5656170

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-jupyter-builder >=0.8.2
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - pip
    - python
  run:
    - ipywidgets >=7.6.0,<9
    - python

test:
  imports:
    - ipylab
  requires:
    - pip
    - jupyterlab >=4.0.0,<5
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | python -c "import re, sys; v = sys.stdin.read(); assert re.search(r'ipylab.*enabled.*ok', v, re.MULTILINE | re.IGNORECASE)"

about:
  home: https://github.com/jtpio/ipylab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - ipylab/labextension/static/third-party-licenses.json
  license_family: BSD
  summary: Control JupyterLab from Python notebooks
  description: Control JupyterLab from Python notebooks
  doc_url: https://ipylab.readthedocs.io
  dev_url: https://github.com/jtpio/ipylab

extra:
  recipe-maintainers:
    - jtpio
    - bollwyvl
